import { Product } from "../types/Product";

export const MOCK_PRODUCTS: Product[] = [
  {
    id: "1",
    name: "Stylish Leather Handbag",
    description: "A chic and spacious leather handbag, perfect for everyday use. Features multiple compartments and a durable design.",
    price: 120.00,
    originalPrice: 150.00,
    imageUrl: "https://via.placeholder.com/300x300/FF5733/FFFFFF?text=Handbag",
    images: [
      "https://via.placeholder.com/600x400/FF5733/FFFFFF?text=Handbag+View+1",
      "https://via.placeholder.com/600x400/C70039/FFFFFF?text=Handbag+View+2",
      "https://via.placeholder.com/600x400/900C3F/FFFFFF?text=Handbag+View+3",
    ],
    category: "Fashion",
    condition: "New",
    shippingOptions: ["Standard", "Express"],
    paymentOptions: ["Credit Card", "PayPal"],
    sellerInfo: { id: "s1", name: "Fashionista Store", rating: 4.8 },
  },
  {
    id: "2",
    name: "Wireless Bluetooth Headphones",
    description: "Immersive sound experience with noise-cancellation. Long-lasting battery and comfortable fit for all-day listening.",
    price: 75.00,
    originalPrice: 90.00,
    imageUrl: "https://via.placeholder.com/300x300/33FF57/FFFFFF?text=Headphones",
    images: [
      "https://via.placeholder.com/600x400/33FF57/FFFFFF?text=Headphones+View+1",
      "https://via.placeholder.com/600x400/00C739/FFFFFF?text=Headphones+View+2",
      "https://via.placeholder.com/600x400/00903F/FFFFFF?text=Headphones+View+3",
    ],
    category: "Electronics",
    condition: "New",
    shippingOptions: ["Standard"],
    paymentOptions: ["Credit Card"],
    sellerInfo: { id: "s2", name: "Tech Gadgets Inc.", rating: 4.5 },
  },
  {
    id: "3",
    name: "Vintage Denim Jacket",
    description: "Classic denim jacket, pre-loved with a unique worn-in feel. A timeless piece for any wardrobe.",
    price: 45.00,
    originalPrice: null,
    imageUrl: "https://via.placeholder.com/300x300/3357FF/FFFFFF?text=Jacket",
    images: [
      "https://via.placeholder.com/600x400/3357FF/FFFFFF?text=Jacket+View+1",
      "https://via.placeholder.com/600x400/0039C7/FFFFFF?text=Jacket+View+2",
    ],
    category: "Fashion",
    condition: "Used",
    shippingOptions: ["Standard"],
    paymentOptions: ["Credit Card", "Cash on Delivery"],
    sellerInfo: { id: "s3", name: "Retro Finds", rating: 4.2 },
  },
  {
    id: "4",
    name: "Organic Green Tea Set",
    description: "A selection of premium organic green teas, perfect for a relaxing evening. Includes a ceramic teapot and two cups.",
    price: 30.00,
    originalPrice: null,
    imageUrl: "https://via.placeholder.com/300x300/FF33A1/FFFFFF?text=Tea+Set",
    images: [
      "https://via.placeholder.com/600x400/FF33A1/FFFFFF?text=Tea+Set+View+1",
      "https://via.placeholder.com/600x400/C7007F/FFFFFF?text=Tea+Set+View+2",
    ],
    category: "Home & Kitchen",
    condition: "New",
    shippingOptions: ["Standard"],
    paymentOptions: ["Credit Card", "PayPal"],
    sellerInfo: { id: "s4", name: "Healthy Living Co.", rating: 4.9 },
  },
  {
    id: "5",
    name: "Professional Camera Lens",
    description: "High-quality prime lens for professional photography. Excellent low-light performance and sharp images.",
    price: 450.00,
    originalPrice: 500.00,
    imageUrl: "https://via.placeholder.com/300x300/A133FF/FFFFFF?text=Camera+Lens",
    images: [
      "https://via.placeholder.com/600x400/A133FF/FFFFFF?text=Lens+View+1",
      "https://via.placeholder.com/600x400/7F00C7/FFFFFF?text=Lens+View+2",
    ],
    category: "Electronics",
    condition: "Used",
    shippingOptions: ["Express"],
    paymentOptions: ["Credit Card", "Bank Transfer"],
    sellerInfo: { id: "s5", name: "Pro Gear Shop", rating: 4.7 },
  },
];

export const MOCK_CATEGORIES = [
  "Fashion",
  "Electronics",
  "Home & Kitchen",
  "Books",
  "Sports",
  "Beauty",
  "Automotive",
  "Collectibles",
];
